apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso-tc-trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - image: cutibo29/trips:latest
          name: trips
          env:
            - name: DB_PORT
              value: "1433"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: database-url
            - name: DB_UPDATE_TYPE
              value: update
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: rso-tc-trips
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: trips